services:

  elasticsearch:
    image: mirror.gcr.io/library/elasticsearch:7.17.1
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    container_name: kibana
    image: kibana:7.4.0
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - ./minio-storage:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  postgres:
    container_name: postgres
    image: postgres:16.3
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "5432"
      POSTGRES_DB: "car_booking_service"
    volumes:
      - ./app_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    container_name: server 
    build:
      context: .
    environment:
      HOST: "0.0.0.0"
      PORT: "8000"
      MINIO_HOST: "minio"
      MINIO_PORT: "9000"
      MINIO_USER: "minio"
      MINIO_PASSWORD: "minio123"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "5432"
      POSTGRES_DATABASE: "car_booking_service"
    depends_on:
      - postgres
      - minio
    ports:
      - "8000:8000"
    restart: always
