version: "3.7"
services:
  database:
    image: romanchechyotkin/car_booking_service_postgresql
    restart: always
    environment:
      POSTGRES_DB: car_booking_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5432
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  server:
    image: romanchechyotkin/car_booking_service_backend
    depends_on:
      - database
    networks:
      - default
    ports:
      - "5000:5000"

volumes:
  data:
